require 'date'
#
u1 = User.create!(name: "who", email: "kill@me", password: "password", password_confirmation: "password", image: File.open(File.join(Rails.root, "db/images/alexchin.jpg")))
u2 = User.create!(name: "Dude", email: "fuck@this", password: "password", password_confirmation: "password",image: File.open(File.join(Rails.root, "db/images/alexchin2.jpg")))
u3 = User.create!(name: "Dev", email: "dev@patel", password: "password", password_confirmation: "password",image: File.open(File.join(Rails.root, "db/images/devpatel.jpg")))
u4 = User.create!(name: "Jake", email: "jake@jake", password: "password", password_confirmation: "password", image: File.open(File.join(Rails.root, "db/images/cooldog.jpg")))
u5 = User.create!(name: "CoolDog", email: "cool@dog", password: "password", password_confirmation: "password",image: File.open(File.join(Rails.root, "db/images/coolerdog.jpg")))
u6 = User.create!(name: "Drildo", email: "drill@do", password: "password", password_confirmation: "password",image: File.open(File.join(Rails.root, "db/images/coolestdog.jpg")))

c1 = Category.create!(name: "Habitat restoration")
c2 = Category.create!(name: "Environmentalism")
c3 = Category.create!(name: "Conservation")
c4 = Category.create!(name: "Urban revitalisation")
c5 = Category.create!(name: "Pet and Animal Welfare")
c6 = Category.create!(name: "Zoos and Aquariums")
c7 = Category.create!(name: "Education")

p1 = Project.create!(title: "Help the whales eat more nutrients", user_id: 3, category_id: 2, end_date: Date.new(2017, 4, 27), brief: "I'm going to throw meat into the sea so the whales can get more nutrients, I think a pack of 6 richmonds pork saussages should do the trick!!", image: File.open(File.join(Rails.root, "db/images/whales.jpg")), video: "https://www.youtube.com/embed/XGSy3_Czz8k?playlist=XGSy3_Czz8k&loop=1", target_amount: 500 )
p2 = Project.create!(title: "Clean up this stinking city", user_id: 4, category_id: 2, end_date: Date.new(2017, 4, 28), brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in urna augue. Integer eleifend consectetur sem. Fusce sit amet mauris vitae metus malesuada sollicitudin. Nunc fringilla, purus ac eleifend laoreet, magna ante finibus urna, ut fringilla urna dui vel metus. Curabitur in lectus sit amet urna interdum venenatis et eget quam. Nulla sodales metus rhoncus, tincidunt dui at, egestas quam. Ut in porta felis. In eget quam consectetur, pharetra enim eget, viverra lacus. Nam quis elit mollis, imperdiet ex et, auctor ante. Quisque imperdiet dignissim dolor et molestie. Vestibulum dapibus turpis sem, at imperdiet urna maximus ac. Vivamus et mi sit amet nunc iaculis dictum. Etiam sed erat sed leo accumsan facilisis sed a lectus. Morbi consectetur, urna pharetra aliquam auctor, dolor justo vulputate sem, faucibus aliquam enim tellus ac urna. Sed eleifend nisi vitae accumsan viverra. Nullam lorem risus, porttitor id erat vel, ultrices faucibus ante. Mauris nunc ipsum, interdum vel risus eget, tincidunt euismod dolor. Morbi faucibus tincidunt consectetur. Donec arcu lacus, faucibus venenatis est in, aliquam gravida nulla. Curabitur nulla ipsum, lacinia eget posuere vel, aliquam eu lectus.", image: File.open(File.join(Rails.root, "db/images/rubbish.jpg")), video: "https://www.youtube.com/embed/vAPEs5i94Ck", target_amount: 20 )
p3 = Project.create!(title: "Ducks aren't breeding!", user_id: 2, category_id: 1, end_date: Date.new(2017, 5, 28), brief: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in urna augue. Integer eleifend consectetur sem. Fusce sit amet mauris vitae metus malesuada sollicitudin. Nunc fringilla, purus ac eleifend laoreet, magna ante finibus urna, ut fringilla urna dui vel metus. Curabitur in lectus sit amet urna interdum venenatis et eget quam. Nulla sodales metus rhoncus, tincidunt dui at, egestas quam. Ut in porta felis. In eget quam consectetur, pharetra enim eget, viverra lacus. Nam quis elit mollis, imperdiet ex et, auctor ante. Quisque imperdiet dignissim dolor et molestie. Vestibulum dapibus turpis sem, at imperdiet urna maximus ac. Vivamus et mi sit amet nunc iaculis dictum.", image: File.open(File.join(Rails.root, "db/images/duck.jpg")), video: "https://www.youtube.com/embed/jbzV2Y06G-E", target_amount: 150 )
p4 = Project.create!(title: "Huge Climate change project", user_id: 3, category_id: 4, end_date: Date.new(2017, 4, 30), brief: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in urna augue. Integer eleifend consectetur sem. Fusce sit amet mauris vitae metus malesuada sollicitudin. Nunc fringilla, purus ac eleifend laoreet, magna ante finibus urna, ut fringilla urna dui vel metus. Curabitur in lectus sit amet urna interdum venenatis et eget quam. Nulla sodales metus rhoncus, tincidunt dui at, egestas quam. Ut in porta felis. In eget quam consectetur, pharetra enim eget, viverra lacus. Nam quis elit mollis, imperdiet ex et, auctor ante. Quisque imperdiet dignissim dolor et molestie. Vestibulum dapibus turpis sem, at imperdiet urna maximus ac. Vivamus et mi sit amet nunc iaculis dictum.", image: File.open(File.join(Rails.root, "db/images/ice.jpg")), video: "https://www.youtube.com/embed/jbzV2Y06G-E", target_amount: 500000 )
p5 = Project.create!(title: "Asian Elephant Conservation", user_id: 6, category_id: 3, end_date: Date.new(2017, 7, 20), brief: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in urna augue. Integer eleifend consectetur sem. Fusce sit amet mauris vitae metus malesuada sollicitudin. Nunc fringilla, purus ac eleifend laoreet, magna ante finibus urna, ut fringilla urna dui vel metus. Curabitur in lectus sit amet urna interdum venenatis et eget quam. Nulla sodales metus rhoncus, tincidunt dui at, egestas quam. Ut in porta felis. In eget quam consectetur, pharetra enim eget, viverra lacus. Nam quis elit mollis, imperdiet ex et, auctor ante. Quisque imperdiet dignissim dolor et molestie. Vestibulum dapibus turpis sem, at imperdiet urna maximus ac. Vivamus et mi sit amet nunc iaculis dictum.", image: File.open(File.join(Rails.root, "db/images/elephant.jpg")), video: "https://www.youtube.com/embed/XGSy3_Czz8k?playlist=XGSy3_Czz8k&loop=1", target_amount: 20000 )
p6 = Project.create!(title: "London Aquarium donations for new enclosure", user_id: 5, category_id: 2, end_date: Date.new(2017, 6, 16), brief: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in urna augue. Integer eleifend consectetur sem. Fusce sit amet mauris vitae metus malesuada sollicitudin. Nunc fringilla, purus ac eleifend laoreet, magna ante finibus urna, ut fringilla urna dui vel metus. Curabitur in lectus sit amet urna interdum venenatis et eget quam. Nulla sodales metus rhoncus, tincidunt dui at, egestas quam. Ut in porta felis. In eget quam consectetur, pharetra enim eget, viverra lacus. Nam quis elit mollis, imperdiet ex et, auctor ante. Quisque imperdiet dignissim dolor et molestie. Vestibulum dapibus turpis sem, at imperdiet urna maximus ac. Vivamus et mi sit amet nunc iaculis dictum.", image: File.open(File.join(Rails.root, "db/images/whales2.jpg")), video: "https://www.youtube.com/embed/jbzV2Y06G-E", target_amount: 5000 )
p7 = Project.create!(title: "Teaching Guatemalans about the plight of the native sloths", user_id: 1, category_id: 7, end_date: Date.new(2017, 4, 28), brief: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in urna augue. Integer eleifend consectetur sem. Fusce sit amet mauris vitae metus malesuada sollicitudin. Nunc fringilla, purus ac eleifend laoreet, magna ante finibus urna, ut fringilla urna dui vel metus. Curabitur in lectus sit amet urna interdum venenatis et eget quam. Nulla sodales metus rhoncus, tincidunt dui at, egestas quam. Ut in porta felis. In eget quam consectetur, pharetra enim eget, viverra lacus. Nam quis elit mollis, imperdiet ex et, auctor ante. Quisque imperdiet dignissim dolor et molestie. Vestibulum dapibus turpis sem, at imperdiet urna maximus ac. Vivamus et mi sit amet nunc iaculis dictum.", image: File.open(File.join(Rails.root, "db/images/sloth.jpg")), video: "https://www.youtube.com/embed/jbzV2Y06G-E", target_amount: 500 )
p8 = Project.create!(title: "Habitat restoration", user_id: 3, category_id: 1, end_date: Date.new(2017, 7, 28), brief: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in urna augue. Integer eleifend consectetur sem. Fusce sit amet mauris vitae metus malesuada sollicitudin. Nunc fringilla, purus ac eleifend laoreet, magna ante finibus urna, ut fringilla urna dui vel metus. Curabitur in lectus sit amet urna interdum venenatis et eget quam. Nulla sodales metus rhoncus, tincidunt dui at, egestas quam. Ut in porta felis. In eget quam consectetur, pharetra enim eget, viverra lacus. Nam quis elit mollis, imperdiet ex et, auctor ante. Quisque imperdiet dignissim dolor et molestie. Vestibulum dapibus turpis sem, at imperdiet urna maximus ac. Vivamus et mi sit amet nunc iaculis dictum.", image: File.open(File.join(Rails.root, "db/images/habitat.jpg")), video: "https://www.youtube.com/embed/jbzV2Y06G-E", target_amount: 4050 )


d1 = Donation.create!(user_id: 2, project_id: 1, amount: 25)
d2 = Donation.create!(user_id: 2, project_id: 5, amount: 250)
d3 = Donation.create!(user_id: 3, project_id: 8, amount: 1000)
d4 = Donation.create!(user_id: 4, project_id: 2, amount: 10)
d5 = Donation.create!(user_id: 1, project_id: 3, amount: 30)
d6 = Donation.create!(user_id: 4, project_id: 4, amount: 4000)
d7 = Donation.create!(user_id: 5, project_id: 6, amount: 400)
d8 = Donation.create!(user_id: 6, project_id: 7, amount: 200)
d9 = Donation.create!(user_id: 6, project_id: 2, amount: 5)
d10 = Donation.create!(user_id: 1, project_id: 1, amount: 250)
